target 'ReactiveEstimote', :exclusive => true do
  pod "ReactiveEstimote", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ReactiveEstimote", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta', :branch => '0.3-wip'
  pod 'Expecta'
  pod 'OCMock'
end
