language: objective-c
xcode_sdk: iphonesimulator
xcode_workspace: Example/ReactiveEstimote.xcworkspace
xcode_scheme: ReactiveEstimote
before_script:
  - export LANG=en_US.UTF-8
  - gem i slather --no-ri --no-rdoc
before_install: cd Example && pod install && cd $TRAVIS_BUILD_DIR
script:
- xcodebuild test -workspace Example/ReactiveEstimote.xcworkspace -scheme ReactiveEstimote -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
after_success: slather
